# Set update schedule for dependencies

version: 2
updates:

  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/music_tag_editor" # Location of package manifests
    schedule:
      interval: "daily"
    # Add reviewers
    reviewers:
      - "joaomagdaleno"
    # Add assignees
    assignees:
      - "joaomagdaleno"
    # Set a PR limit for version updates
    # to avoid overwhelming your inbox
    open-pull-requests-limit: 10
    # Specify labels for Dependabot PRs
    labels:
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    # Add reviewers
    reviewers:
      - "joaomagdaleno"
    # Add assignees
    assignees:
      - "joaomagdaleno"
    # Set a PR limit for version updates
    # to avoid overwhelming your inbox
    open-pull-requests-limit: 10
    # Specify labels for Dependabot PRs
    labels:
      - "dependencies"
      - "dependabot"
      - "github-actions"
