name: music_tag_editor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dart_tags: ^0.4.1
  file_picker: ^8.0.7
  http: ^1.2.1
  sqflite: ^2.3.3
  path: ^1.9.0
  archive: ^3.6.1
  just_audio: ^0.10.5
  audio_session: ^0.1.21
  nearby_connections: ^4.3.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.2.3
  system_tray: ^2.0.3
  window_manager: ^0.5.1
  audio_service: ^0.18.18
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  network_info_plus: ^7.0.0
  xml: ^6.6.1
  firebase_core: ^3.8.1
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.2.0
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  connectivity_plus: ^6.1.1
  palette_generator_master: ^1.0.1
  meta: ^1.11.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  sqflite_common_ffi: ^2.3.3
  flutter_lints: ^5.0.0
  alchemist: ^0.13.0

flutter:
  uses-material-design: true
