name: music_tag_editor
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  package_info_plus: ^9.0.0
  http: ^1.6.0
  path_provider: ^2.1.3
  pub_semver: ^2.1.4
  url_launcher: ^6.3.0
  media_kit: ^1.2.3
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  sqflite: ^2.3.0
  file_picker: ^10.3.6
  path: ^1.8.3
  metadata_god: ^1.1.0
  fluent_ui: ^4.8.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
